[package]
name = "alhc"
version = "0.2.0"
authors = ["Steve Xiao <stevexmh@qq.com>"]
homepage = "https://github.com/Steve-xmh/alhc"
repository = "https://github.com/Steve-xmh/alhc"
description = "Async Lightweight HTTP Client: A async http client library that using system library to reduce binary size if possible."
keywords = ["http", "client", "request", "async"]
categories = ["web-programming", "web-programming::http-client"]
edition = "2021"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.42.0", features = [
    "Win32_Foundation",
    "Win32_Networking_WinHttp",
]}

[target.'cfg(target_os = "macos")'.dependencies]
# objc = { version =  "0.2", features = ["exception"] }
# cocoa = "0.24"
# once_cell = "1.16.0"
core-foundation = "0.9"

[dev-dependencies]
pollster = "0.2.5"

[target.'cfg(target_os = "macos")'.dev-dependencies]
bindgen = "*"

[dependencies]
futures = "0.3.25"
pin-project-lite = "0.2.9"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
debug = false
strip = true
