[package]
name = "alhc"
version = "0.1.0"
authors = ["Steve Xiao <stevexmh@qq.com>"]
edition = "2021"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.42.0", features = [
    "Win32_Foundation",
    "Win32_Networking_WinHttp",
]}

[dev-dependencies]
futures = "0.3.25"
pollster = "0.2.5"

[dependencies]
futures-io = "0.3.25"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
debug = false
strip = true
